# Generated by Django 5.0.4 on 2024-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(blank=True, max_length=100, null=True)),
                ('proname', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=tuple)),
                ('pimage', models.ImageField(null=True, upload_to='category image')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
