# Generated by Django 5.0.4 on 2024-05-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_prodb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedb',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prodb',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=tuple),
        ),
    ]
